import { type CH5VolumeSliderProps } from "@/components/lib/volume/CH5Volume";
import {
  Volume2, Music, Tv, Mic, Speaker, Headphones,
} from "lucide-react";

export const AUDIO_CONTROLS: CH5VolumeSliderProps[] = [
  {
    id: "master",
    label: "Master Volume",
    icon: <Volume2 />,
    description: "Controls all audio output",
    volumeCommandSignal: "Audio.Master_Volume",
    volumeFeedbackSignal: "Audio.Master_Volume_FB",
    muteCommandSignal: "Audio.Master_Mute",
    muteFeedbackSignal: "Audio.Master_Mute_FB",
  },
  {
    id: "tv",
    label: "Television",
    icon: <Tv />,
    volumeCommandSignal: "Audio.Volume1",
    volumeFeedbackSignal: "Audio.Volume1_FB",
    muteCommandSignal: "Audio.Volume1Mute",
    muteFeedbackSignal: "Audio.Volume1Mute_FB",
  },
  {
    id: "music",
    label: "Music",
    icon: <Music />,
    volumeCommandSignal: "Audio.Volume2",
    volumeFeedbackSignal: "Audio.Volume2_FB",
    muteCommandSignal: "Audio.Volume2Mute",
    muteFeedbackSignal: "Audio.Volume2Mute_FB",
  },
  {
    id: "speakers",
    label: "Speakers",
    icon: <Speaker />,
    volumeCommandSignal: "Audio.Volume3",
    volumeFeedbackSignal: "Audio.Volume3_FB",
    muteCommandSignal: "Audio.Volume3Mute",
    muteFeedbackSignal: "Audio.Volume3Mute_FB",
  },
  {
    id: "headphones",
    label: "Headphones",
    icon: <Headphones />,
    volumeCommandSignal: "Audio.Volume4",
    volumeFeedbackSignal: "Audio.Volume4_FB",
    muteCommandSignal: "Audio.Volume4Mute",
    muteFeedbackSignal: "Audio.Volume4Mute_FB",
  },
  {
    id: "microphone",
    label: "Microphone",
    icon: <Mic />,
    volumeCommandSignal: "Audio.Volume5",
    volumeFeedbackSignal: "Audio.Volume5_FB",
    muteCommandSignal: "Audio.Volume5Mute",
    muteFeedbackSignal: "Audio.Volume5Mute_FB",
  },
  {
    id: "microphone",
    label: "Microphone",
    icon: <Mic />,
    volumeCommandSignal: "Audio.Volume6",
    volumeFeedbackSignal: "Audio.Volume6_FB",
    muteCommandSignal: "Audio.Volume6Mute",
    muteFeedbackSignal: "Audio.Volume6Mute_FB",
  },
];
