import { type CH5VolumeSliderProps } from "@/components/lib/volume/CH5Volume";
import { 
  Volume2, Music, Tv, Mic, Speaker, Headphones,
} from "lucide-react";

export const AUDIO_CONTROLS: CH5VolumeSliderProps[] = [
  {
    id: "master",
    label: "Master Volume",
    icon: <Volume2 />,
    description: "Controls all audio output",
    volumeCommandSignal: "Audio.Master_Volume",
    volumeFeedbackSignal: "Audio.Master_Volume_FB",
    muteCommandSignal: "Audio.Master_Mute",
    muteFeedbackSignal: "Audio.Master_Mute_FB",
  },
  {
    id: "tv",
    label: "Television",
    icon: <Tv />,
    volumeCommandSignal: "Audio.Volume_1",
    volumeFeedbackSignal: "Audio.Volume_1_FB",
    muteCommandSignal: "Audio.Volume_1_Mute",
    muteFeedbackSignal: "Audio.Volume_1_Mute_FB",
  },
  {
    id: "music",
    label: "Music",
    icon: <Music />,
    volumeCommandSignal: "Audio.Volume_2",
    volumeFeedbackSignal: "Audio.Volume_2_FB",
    muteCommandSignal: "Audio.Volume_2_Mute",
    muteFeedbackSignal: "Audio.Volume_2_Mute_FB",
  },
  {
    id: "speakers",
    label: "Speakers",
    icon: <Speaker />,
    volumeCommandSignal: "Audio.Volume_3",
    volumeFeedbackSignal: "Audio.Volume_3_FB",
    muteCommandSignal: "Audio.Volume_3_Mute",
    muteFeedbackSignal: "Audio.Volume_3_Mute_FB",
  },
  {
    id: "headphones",
    label: "Headphones",
    icon: <Headphones />,
    volumeCommandSignal: "Audio.Volume_4",
    volumeFeedbackSignal: "Audio.Volume_4_FB",
    muteCommandSignal: "Audio.Volume_4_Mute",
    muteFeedbackSignal: "Audio.Volume_4_Mute_FB",
  },
  {
    id: "microphone",
    label: "Microphone",
    icon: <Mic />,
    volumeCommandSignal: "Audio.Volume_5",
    volumeFeedbackSignal: "Audio.Volume_5_FB",
    muteCommandSignal: "Audio.Volume_5_Mute",
    muteFeedbackSignal: "Audio.Volume_5_Mute_FB",
  },
  {
    id: "microphone",
    label: "Microphone",
    icon: <Mic />,
    volumeCommandSignal: "Audio.Volume_6",
    volumeFeedbackSignal: "Audio.Volume_6_FB",
    muteCommandSignal: "Audio.Volume_6_Mute",
    muteFeedbackSignal: "Audio.Volume_6_Mute_FB",
  },
];
