import { type RoutingItem } from "../pages/RoutingPage";
import { 
  Tv, Gamepad2, Laptop, Smartphone, Disc, MonitorPlay,
  Speaker, Headphones, Radio, 
} from "lucide-react";

export const SOURCES: RoutingItem[] = [
  {
    id: "source1",
    label: "Source 1",
    icon: <Tv />,
    description: "4K Streaming",
    commandSignal: "routing.source.source1",
    feedbackSignal: "routing.source.source1.fb",
  },
  {
    id: "source2",
    label: "Source 2",
    icon: <Gamepad2 />,
    description: "Gaming Console",
    commandSignal: "routing.source.source2",
    feedbackSignal: "routing.source.source2.fb",
  },
  {
    id: "source3",
    label: "Source 3",
    icon: <Laptop />,
    description: "HDMI Input",
    commandSignal: "routing.source.source3",
    feedbackSignal: "routing.source.source3.fb",
  },
  {
    id: "source4",
    label: "Source 4",
    icon: <Smartphone />,
    description: "AirPlay",
    commandSignal: "routing.source.source4",
    feedbackSignal: "routing.source.source4.fb",
  },
  {
    id: "source5",
    label: "Source 5",
    icon: <Disc />,
    description: "Disc Player",
    commandSignal: "routing.source.source5",
    feedbackSignal: "routing.source.source5.fb",
  },
  {
    id: "source6",
    label: "Source 6",
    icon: <MonitorPlay />,
    description: "TV Channels",
    commandSignal: "routing.source.source6",
    feedbackSignal: "routing.source.source6.fb",
  },
  {
    id: "source7",
    label: "Source 7",
    icon: <MonitorPlay />,
    description: "TV Channels",
    commandSignal: "routing.source.source7",
    feedbackSignal: "routing.source.source7.fb",
  },
];

export const DESTINATIONS: RoutingItem[] = [
  {
    id: "dest1",
    label: "Destination 1",
    icon: <Tv />,
    description: "75\" Display",
    commandSignal: "routing.dest.dest1",
    feedbackSignal: "routing.dest.dest1.fb",
  },
  {
    id: "dest2",
    label: "Destination 2",
    icon: <Tv />,
    description: "55\" Display",
    commandSignal: "routing.dest.dest2",
    feedbackSignal: "routing.dest.dest2.fb",
  },
  {
    id: "dest3",
    label: "Destination 3",
    icon: <Tv />,
    description: "43\" Display",
    commandSignal: "routing.dest.dest3",
    feedbackSignal: "routing.dest.dest3.fb",
  },
  {
    id: "dest4",
    label: "Destination 4",
    icon: <Speaker />,
    description: "Audio Only",
    commandSignal: "routing.dest.dest4",
    feedbackSignal: "routing.dest.dest4.fb",
  },
  {
    id: "dest5",
    label: "Destination 5",
    icon: <Headphones />,
    description: "Wireless",
    commandSignal: "routing.dest.dest5",
    feedbackSignal: "routing.dest.dest5.fb",
  },
  {
    id: "dest6",
    label: "Destination 6",
    icon: <Radio />,
    description: "Outdoor",
    commandSignal: "routing.dest.dest6",
    feedbackSignal: "routing.dest.dest6.fb",
  },
];