import { type RoutingItem } from "../pages/RoutingPage";
import { 
  Tv, Gamepad2, Laptop, Smartphone, Disc, MonitorPlay,
  Speaker, Headphones, Radio, 
} from "lucide-react";

export const SOURCES: RoutingItem[] = [
  {
    id: "source1",
    label: "Source 1",
    icon: <Tv />,
    description: "4K Streaming",
    commandSignal: "routing.source1",
    feedbackSignal: "routing.source1_fb",
  },
  {
    id: "source2",
    label: "Source 2",
    icon: <Gamepad2 />,
    description: "Gaming Console",
    commandSignal: "routing.source2",
    feedbackSignal: "routing.source2_fb",
  },
  {
    id: "source3",
    label: "Source 3",
    icon: <Laptop />,
    description: "HDMI Input",
    commandSignal: "routing.source3",
    feedbackSignal: "routing.source3_fb",
  },
  {
    id: "source4",
    label: "Source 4",
    icon: <Smartphone />,
    description: "AirPlay",
    commandSignal: "routing.source4",
    feedbackSignal: "routing.source4_fb",
  },
  {
    id: "source5",
    label: "Source 5",
    icon: <Disc />,
    description: "Disc Player",
    commandSignal: "routing.source5",
    feedbackSignal: "routing.source5_fb",
  },
  {
    id: "source6",
    label: "Source 6",
    icon: <MonitorPlay />,
    description: "TV Channels",
    commandSignal: "routing.source6",
    feedbackSignal: "routing.source6_fb",
  },
  {
    id: "source7",
    label: "Source 7",
    icon: <MonitorPlay />,
    description: "TV Channels",
    commandSignal: "routing.source7",
    feedbackSignal: "routing.source7_fb",
  },
];

export const DESTINATIONS: RoutingItem[] = [
  {
    id: "dest1",
    label: "Destination 1",
    icon: <Tv />,
    description: "75\" Display",
    commandSignal: "routing.dest1",
    feedbackSignal: "routing.dest1_fb",
  },
  {
    id: "dest2",
    label: "Destination 2",
    icon: <Tv />,
    description: "55\" Display",
    commandSignal: "routing.dest2",
    feedbackSignal: "routing.dest2_fb",
  },
  {
    id: "dest3",
    label: "Destination 3",
    icon: <Tv />,
    description: "43\" Display",
    commandSignal: "routing.dest3",
    feedbackSignal: "routing.dest3_fb",
  },
  {
    id: "dest4",
    label: "Destination 4",
    icon: <Speaker />,
    description: "Audio Only",
    commandSignal: "routing.dest4",
    feedbackSignal: "routing.dest4_fb",
  },
  {
    id: "dest5",
    label: "Destination 5",
    icon: <Headphones />,
    description: "Wireless",
    commandSignal: "routing.dest5",
    feedbackSignal: "routing.dest5_fb",
  },
  {
    id: "dest6",
    label: "Destination 6",
    icon: <Radio />,
    description: "Outdoor",
    commandSignal: "routing.dest6",
    feedbackSignal: "routing.dest6_fb",
  },
];