import { type RoutingItem } from "../pages/RoutingPage";
import { 
  Tv, Gamepad2, Laptop, Smartphone, Disc, MonitorPlay,
  Speaker, Headphones, Radio, 
} from "lucide-react";

export const SOURCES: RoutingItem[] = [
  {
    id: "source1",
    label: "Apple TV",
    icon: <Tv />,
    description: "4K Streaming",
    commandSignal: "routing.source.appletv",
    feedbackSignal: "routing.source.appletv.fb",
  },
  {
    id: "source2",
    label: "Barco Clickshare",
    icon: <Gamepad2 />,
    description: "Gaming Console",
    commandSignal: "routing.source.xbox",
    feedbackSignal: "routing.source.xbox.fb",
  },
  {
    id: "source3",
    label: "Conference PC",
    icon: <Laptop />,
    description: "HDMI Input",
    commandSignal: "routing.source.laptop",
    feedbackSignal: "routing.source.laptop.fb",
  },
  {
    id: "source4",
    label: "HDMI 1",
    icon: <Smartphone />,
    description: "AirPlay",
    commandSignal: "routing.source.phone",
    feedbackSignal: "routing.source.phone.fb",
  },
  {
    id: "source5",
    label: "HDMI 2",
    icon: <Disc />,
    description: "Disc Player",
    commandSignal: "routing.source.bluray",
    feedbackSignal: "routing.source.bluray.fb",
  },
  {
    id: "source6",
    label: "HDMI 3",
    icon: <MonitorPlay />,
    description: "TV Channels",
    commandSignal: "routing.source.cable",
    feedbackSignal: "routing.source.cable.fb",
  },
  {
    id: "source7",
    label: "HDMI 4",
    icon: <MonitorPlay />,
    description: "TV Channels",
    commandSignal: "routing.source.cable",
    feedbackSignal: "routing.source.cable.fb",
  },
];

export const DESTINATIONS: RoutingItem[] = [
  {
    id: "livingroom",
    label: "Living Room",
    icon: <Tv />,
    description: "75\" Display",
    commandSignal: "routing.dest.livingroom",
    feedbackSignal: "routing.dest.livingroom.fb",
  },
  {
    id: "bedroom",
    label: "Bedroom",
    icon: <Tv />,
    description: "55\" Display",
    commandSignal: "routing.dest.bedroom",
    feedbackSignal: "routing.dest.bedroom.fb",
  },
  {
    id: "kitchen",
    label: "Kitchen",
    icon: <Tv />,
    description: "43\" Display",
    commandSignal: "routing.dest.kitchen",
    feedbackSignal: "routing.dest.kitchen.fb",
  },
  {
    id: "speakers",
    label: "Speakers",
    icon: <Speaker />,
    description: "Audio Only",
    commandSignal: "routing.dest.speakers",
    feedbackSignal: "routing.dest.speakers.fb",
  },
  {
    id: "headphones",
    label: "Headphones",
    icon: <Headphones />,
    description: "Wireless",
    commandSignal: "routing.dest.headphones",
    feedbackSignal: "routing.dest.headphones.fb",
  },
  {
    id: "patio",
    label: "Patio",
    icon: <Radio />,
    description: "Outdoor",
    commandSignal: "routing.dest.patio",
    feedbackSignal: "routing.dest.patio.fb",
  },
];